# -*- coding: utf-8 -*-
"""Eğlenceli 4 işlem.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/100cFWDogjOz93h5vcGBKsRurMOCtdpl6
"""

#import random ile rastgele sayı yapma eklentisini ekliyoruz
import random

#değişkenler
matsayi1=random.randint(3,5)
matsayi2=random.randint(3,5)
matmakcevap=matsayi1*matsayi2

#bize problemi verecek olan kod:
print(matsayi1,"x",matsayi2,"=")

#cevabı soran girişli değişken
matcevap = input("cevabı girin ")

#doğru cevabı gösteren kod
print ("doğru cevap",matmakcevap)

#import random ile rastgele sayı yapma eklentisini ekliyoruz
import random

#değişkenler
matsayi1=random.randint(3,5)
matsayi2=random.randint(3,5)
matmakcevap=matsayi1+matsayi2

#bize problemi verecek olan kod:
print(matsayi1,"+",matsayi2,"=")

#cevabı soran girişli değişken
matcevap = input("cevabı girin ")

#doğru cevabı gösteren kod
print ("doğru cevap",matmakcevap)

#import random ile rastgele sayı yapma eklentisini ekliyoruz
import random

#değişkenler
matsayi1=random.randint(3,5)
matsayi2=random.randint(3,5)
matmakcevap=matsayi1-matsayi2

#bize problemi verecek olan kod:
print(matsayi1,"-",matsayi2,"=")

#cevabı soran girişli değişken
matcevap = input("cevabı girin ")

#doğru cevabı gösteren kod
print ("doğru cevap",matmakcevap)

#import random ile rastgele sayı yapma eklentisini ekliyoruz
import random

#değişkenler
matsayi1=random.randint(3,5)
matsayi2=random.randint(3,5)
matmakcevap=matsayi1/matsayi2

#bize problemi verecek olan kod:
print(matsayi1,"/",matsayi2,"=")

#cevabı soran girişli değişken
matcevap = input("cevabı girin ")

#doğru cevabı gösteren kod
print ("doğru cevap",matmakcevap)